### ISSUE TITLE
issue with adding items to cart after sorting

### ISSUE THREAD

**Issue by WillBarham** [DThumma/Thumma_CSCI2270_FinalProject#1]
When I add an item to the cart after first selecting "Sort Inventory Alphabetically" and then print the shopping cart, the wrong item has been added to the shopping cart. I noticed that when I added "Woven Drawstring shirt" after sorting and then printed the cart, "Embroidered Espadrilles" had been added to the cart instead. Likewise, if I add "Embroidered Espadrilles" to the cart after sorting, when I print the cart, "Woven Drawstring shirt" has been added. 

Upon further checking, after having selected sort, I noticed that when I search the name of an item, a different item is printed. 

For example, when I search for "Woven Drawstring shirt" before sorting, I get:
Name: Woven Drawstring shirt
Type: shirt
Color: blue
Style: boho

After sorting, I get:
Name: Embroidered Espadrilles
Type: shirt
Color: blue
Style: boho

Also, when printing the inventory before sorting and after sorting, if you look at the items I have been using as examples, their names appear to have been exchanged. Their descriptions are swapped. 

Since all these bugs have to do with the sorting operation, I would definitely check that for the source of this issue.

I can't tell why this happens, but if I am searching by color and type, after having searched for say black pants items, and going back to main menu, if I go back in to change both color and style search parameters, every now and again the program prints the menu over and over and I have to force the program to quit. I can't figure out why this would happen.

Other than these issues, the program worked very well, had an excellent readme, and clear documentation/presentation.

**Comment by DThumma** [comment]
Thanks for pointing this out! We knew this issue before but forgot to put it in the issues section of the README file, the reason it does that is because the function sorts all the "name"s in the array but doesn't change any of the attached items (colors, types, styles), however we could not find a solution.
